src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'text')]
    private $contenu;

    #[ORM\Column(type: 'datetime')]
    private $dateCommentaire;

    #[ORM\ManyToOne(targetEntity: Sujet::class, inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private $sujet;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'commentaries')]
    #[ORM\JoinColumn(nullable: false)]
    private $User;

    #[ORM\Column(type: 'boolean')]
    private $is_Delete;

    #[ORM\Column(type: 'boolean')]
    private $is_edited;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $dateModification;

    public function __construct()
    {   
        $this->dateCommentaire = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateCommentaire(): ?\DateTimeInterface
    {
        return $this->dateCommentaire;
    }

    public function setDateCommentaire(\DateTimeInterface $dateCommentaire): self
    {
        $this->dateCommentaire = $dateCommentaire;

        return $this;
    }

    public function getSujet(): ?Sujet
    {
        return $this->sujet;
    }

    public function setSujet(?Sujet $sujet): self
    {
        $this->sujet = $sujet;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getIsDelete(): ?bool
    {
        return $this->is_Delete;
    }

    public function setIsDelete(bool $is_Delete): self
    {
        $this->is_Delete = $is_Delete;

        return $this;
    }

    public function getIsEdited(): ?bool
    {
        return $this->is_edited;
    }

    public function setIsEdited(bool $is_edited): self
    {
        $this->is_edited = $is_edited;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->dateModification;
    }

    public function setDateModification(?\DateTimeInterface $dateModification): self
    {
        $this->dateModification = $dateModification;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\Commentaire;
use App\Entity\Sujet;
use App\Form\CommentaireType;
use App\Form\ModifyCommentaireType;
use App\Repository\CategorieRepository;
use App\Repository\CommentaireRepository;
use App\Repository\SujetRepository;
use DateTimeZone;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Form\FormTypeInterface;
use Symfony\Component\Validator\Constraints\Collection;

class DefaultController extends AbstractController 
{
    private $user;
    public function __construct(Security $security)
    {
        $this->user = $security->getUser();
    }


    #[Route("/sujets-{categorie}", name:"liste_sujets", methods:['GET'])]
    public function listeSujets(SujetRepository $sujetRepository, $categorie): Response
    {
        $sujet = $sujetRepository->findOneByIdJoinedToCategory($categorie);

        return $this->render('default/listeSujets.html.twig', [
            'sujets' => $sujet,
            'categorie' => $categorie
        ]);
    }

    #[Route('/', name: 'liste_categories', methods:['GET'])]
    public function listeCategories(CategorieRepository $categorieRepository): Response
    {
        $categories = $categorieRepository->findAll();

        return $this->render('default/index.html.twig', [
            'categories' => $categories,
        ]);
    }

    #[Route("/forum/{id}", name:"vue_sujet", requirements:['id' =>'\d+'])]
    public function vueSujet(Sujet $sujet, SujetRepository $sujetRepository, $id,CommentaireRepository $commentaireRepository, Request $request, EntityManagerInterface $manager): Response
    {
        $test = $this->getUser();
        if($this->user !== null){
            
            $date = new \DateTime('@'.strtotime('now'));
            $date->setTimeZone(new DateTimeZone("Europe/Paris"));

            $commentaire = new Commentaire();
            $commentaire->setDateCommentaire($date);
            $commentaire->setSujet($sujet);
            $commentaire->setUser($test);
            $commentaire->setIsDelete(false);
            $commentaire->setIsEdited(false);
            $form = $this->createForm(CommentaireType::class, $commentaire);
            $form->handleRequest($request);

            if($form->isSubmitted() && $form->isValid()){
                $manager->persist($commentaire);
                $manager->flush();
                return $this->redirectToRoute('vue_sujet', ['id' => $sujet->getId()]);
            }

            return $this->render('default/sujet.html.twig', [
                'sujet' => $sujet,
                'form' => $form->createView(),
                'user' => $test
            ]);
        }
        else {
            return $this->render('default/sujet.html.twig', [
                'sujet' => $sujet,
                'user' => $test
            ]);
        }
    }
    
}

templates/default/ajout.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gourdy - Nouveau Sujet{% endblock %}

{% block body %}
<div class="py-5">
    <div class="container py-5">
        <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
            <div class="col-lg-6 bg-light border border-dark border-3 rounded-3 shadow-lg p-3 mb-5 bg-body">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6 text-center mt-5">
                        <h2 class="text-center">Nouveau sujet</h2>
                    </div>
                </div>
                 <div class="container py-5">
                 {% if not form.vars.valid %}
                    {{ form_start(form, {'attr':{'class':'was-validated'}}) }}
                {% else %}
                    {{ form_start(form) }}
                {% endif %}
                    <div class="mb-3">
                        {{ form_label(form.titre) }}
                        {{ form_widget(form.titre, {'attr': {'class':'form-control'}} ) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.contenu) }}
                        {{ form_widget(form.contenu, {'attr': {'class':'form-control'}} ) }}
                    </div>
                    {{ form_label(form.categories) }}

                    <table class="table border">
                        {% for CategoryField in form.categories %}
                            <tr>
                                <td>{{ form_label(CategoryField) }}</td>
                                <td> {{ form_widget(CategoryField) }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                    {{ form_rest(form) }}
                    <div class="mb-3 text-center">
                        <button class="btn btn-primary" type="submit">Enregistrer</button>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/default/editCommentaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gourdy{% endblock %}

{% block body %}
<div class="py-5">
    <div class="container py-5">
        <div class="row gx-4 gx-lg-5 justify-content-center mb-5">
            <div class="col-lg-6 bg-light border border-dark border-3 rounded-3">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6 text-center mt-5">
                        <h2 class="text-center">Edition du commentaire</h2>
                    </div>
                </div>
                 <div class="container py-5">
                    {{ form_start(form) }}
                    <div class="mb-3">
                        {{ form_label(form.contenu) }}
                        {{ form_widget(form.contenu, {'attr': {'class':'form-control'}} ) }}
                    </div>
                    <div class="mb-3">
                        <label>Pseudo :</label>
                        <input type="text" id="delete_commentaire_pseudo" name="delete_commentaire_form[pseudo]" disabled="disabled" required="required" maxlength="255" class="form-control" value="{{ user }}" />
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.dateCommentaire) }}
                        {{ form_widget(form.dateCommentaire, {'attr': {'class':'form-control', 'format':'d/m/Y'}} ) }}
                    </div>
                    {{ form_rest(form) }}
                    <button class="btn btn-primary" type="submit">Supprimer</button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
</div>
     
{% endblock %}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gourdy{% endblock %}

{% block body %}

<h1 class="text-white text-center py-5">Bienvenue sur Gourdy !</h1>
    <div class="card-group">
        <div class="row mb-5">
        
            {% for categorie in categories %}
                <div class="col-lg-4 col-md-6">
                    <div class="content card mt-4">
                        <a href="{{ path('liste_sujets', {'categorie':categorie.nomCategorie }) }}">
                            <img class="card-img-top content-image img-fluid" src="/images/{{ categorie.image }}" alt="Image de {{ categorie.nomCategorie }}">
                            <div class="content-overlay"></div>
                            <div class="content-details fadeIn-bottom">
                                <h1 class="content-title">{{ categorie.nomCategorie }}</h1>
                            </div>
                        </a>
                        <div class="card-footer text-center" style="transform: rotate(0); background-color : #22427C;">
                            <a href="{{ path('liste_sujets', {'categorie':categorie.nomCategorie }) }}" class="btn btn-link stretched-link text-white text-decoration-none">Voir les sujets sur : {{ categorie.nomCategorie }}</a>
                        </div>
                    </div>
                </div>
                {# <div class="content">
                    <a href="https://unsplash.com/photos/HkTMcmlMOUQ" target="_blank">
                    <div class="content-overlay"></div>
                    <img class="content-image" src="https://images.unsplash.com/photo-1433360405326-e50f909805b3?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&w=1080&fit=max&s=359e8e12304ffa04a38627a157fc3362">
                    <div class="content-details fadeIn-bottom">
                        <h3 class="content-title">This is a title</h3>
                    </div>
                    </a>
                </div> #}

            {% endfor %}
        </div>
    </div>


     
{% endblock %}

templates/default/listeSujets.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gourdy - {{ categorie }} {% endblock %}

{% block body %}

<div class="container pt-5">
<h1 class="text-white p-5">Catégorie > {{ categorie }}</h1>


<div class="py-1 bg-danger rounded"></div><br>
{# {% for sujet in sujets|sort((a, b) => a.n <=> b.n) %}
    <td>{{ sujet.n }}</td> <td>{{ sujet.pseudo}}</td> <td>{{ sujet.titre}}</td><br>
{% endfor %} #}
{% if sujets is empty %}
    <div class="container">
    <h3 class="text-white pt-5">Il n'y a aucun sujet dans cette catégorie</h3>
        <p>
            Créez un nouveau sujet dès maintenant en cliquant ici :
            <a class="" href="{{ path('ajout_sujet') }}">Nouveau sujet</a>
        </p>
    </div> 
{% else %}
{% set cpt = 0 %}

{% set page = app.request.get('page') %}
{% set nbSujet = page*8 %}


    {% if sujets|slice(nbSujet, 8) is empty and page >= 1 %}
    <script>
        location.replace("sujets-{{ categorie }}");
    </script>
    {% endif %}
<table id="dtBasicExample" class="table table-hover bg-light border border-1 border-dark" cellspacing="0">
    <thead class="table-dark">
        <tr>
            <th class="col-xl-5">Titre du sujet</th>
            <th scope="col">Pseudo</th>
            <th scope="col">Date de création</th>
            <th scope="col">Nombre de messages</th>
            <th scope="col">Dernier commentaire</th>
        </tr>
        </thead>
    <tbody>
        {% for sujet in sujets|slice(nbSujet, 8) %}
            <tr>
                <th scope="row"><a class="text-decoration-none" href="{{ path('vue_sujet', {'id':sujet.id }) }}">{{ sujet.titre }}</a></th>
                <td>{{ sujet.pseudo }} {% if sujet.roles == ['ROLE_ADMIN'] %}<span class="badge bg-danger">Admin</span>{% endif %}</td>
                <td>{{ sujet.dateCreation|date('d/m/Y') }}</td>
                <td>{{ sujet.n }}</td>
                <td>{% if sujet.d == null %}Aucun message envoyé.{% else %}{{ sujet.d|date('d/m/Y  à H:i:s' ) }}{% endif %}</td>
                
                
            </tr>

    {# <div class="mt-1 border border-2 border-primary">
        <div class="card-body rounded row bg-light">
            <div class="col-7">
            <a class="text-decoration-none" href="{{ path('vue_sujet', {'id':sujet.id }) }}">{{ sujet.titre }}</a><br>
            </div>
            <div class="col">
            <small class="text-muted"> par {{ sujet.pseudo }}</small><br>
            </div>
            <div class="col">
            <small class="text-muted">le {{ sujet.dateCreation|date('d/m/Y') }}</small><br>
            </div>
            <div class="col">
            {{ sujet.n }}
            </div>
        </div>
    </div> #}

    {# <div class="card mt-2">
        <div class="card-body bg-light">
            <a class="text-decoration-none" href="{{ path('vue_sujet', {'id':sujet.id }) }}">{{ sujet.titre }}</a><br>
            <small class="text-muted"> par {{ sujet.pseudo }} le {{ sujet.dateCreation|date('d/m/Y') }}</small><br>
                {{ sujet.n}}
            
            </div>
        </div> #}
        {% set cpt = (cpt)+1 %} 
        {% endfor %}<br>
      </tbody>
</table>

    {# <div class="text-center">
        {% if sujets|length > 10 %}
            {% set test = sujets|length/10%10 %}
            {% if sujets|length is divisible by(10) %}
                {% for i in 0..test-1 %}
                    <a class="btn btn-primary text-white {% if page == i %}active{% endif %}" href="?page={{ i }}">{{ i+1 }}</a>
                {% endfor %}
            {% else %}
                {% for i in 0..test %}
                    <a class="btn btn-primary text-white {% if page == i %}active{% endif %}" href="?page={{ i }}">{{ i+1 }}</a> 
                {% endfor %}
            {% endif %}
        {% endif %}
    </div><br> #}
    <nav>
        <ul class="pagination justify-content-center mt-5">
            {% set test = sujets|length/8%8 %}
            {% if sujets|length is divisible by(8) %}
                {% for i in 0..test-1 %}
                    <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="?page={{ i }}">{{ i+1 }}</a></li>
                {% endfor %}
            {% else %}
                {% for i in 0..test %}
                    <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="?page={{ i }}">{{ i+1 }}</a></li>
                {% endfor %}
            {% endif %}
            {# <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li> #}
        
        </ul>
    </nav>
    {% endif %}
    </div>
{% endblock %}

templates/default/mesSujets.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gourdy - Mes Sujets{% endblock %}

{% block body %}

<div class="container pt-5">
<h1 class="text-white p-5">Mes Sujets</h1>


<div class="py-1 bg-danger rounded"></div><br>

{% if sujets is empty %}
    <div class="container">
    <h3 class="text-white pt-5">Vous n'avez créé aucun sujet.</h3>
        <p class="text-white">
            Créez un nouveau sujet dès maintenant en cliquant ici :
            <a class="btn btn-primary" href="{{ path('ajout_sujet') }}">Nouveau sujet</a>
        </p>
    </div> 
{% else %}
        {% set cpt = 0 %}

        {% set page = app.request.get('page') %}
        {% set nbSujet = page*8 %}


            {% if sujets|slice(nbSujet, 8) is empty and page >= 1 %}
            <script>
                location.replace("sujets-{{ categorie }}");
            </script>
            {% endif %}
        <table class="table table-hover bg-light border border-1 border-dark">
            <thead class="table-dark">
                <tr>
                    <th class="col-xl-5">Titre du sujet</th>
                    <th scope="col">Date de création</th>
                    <th scope="col">Nombre de messages</th>
                    <th scope="col">Dernier commentaire</th>
                </tr>
                </thead>
            <tbody>
                {% for sujet in sujets|slice(nbSujet, 8) %}
                    <tr>
                        <th scope="row"><a class="text-decoration-none" href="{{ path('vue_sujet', {'id':sujet.id }) }}">{{ sujet.titre }}</a></th>
                        <td>{{ sujet.dateCreation|date('d/m/Y') }}</td>
                        <td>{{ sujet.n }}</td>
                        <td>{% if sujet.d == null %}Aucun message envoyé.{% else %}{{ sujet.d|date('d/m/Y  à H:i:s' ) }}{% endif %}</td>
                    </tr>
                {% set cpt = (cpt)+1 %} 
                {% endfor %}<br>
            </tbody>
        </table>

        <nav>
                <ul class="pagination justify-content-center mt-5">
                    {% set test = sujets|length/8%8 %}
                    {% if sujets|length is divisible by(8) %}
                        {% for i in 0..test-1 %}
                            <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="?page={{ i }}">{{ i+1 }}</a></li>
                        {% endfor %}
                    {% else %}
                        {% for i in 0..test %}
                            <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="?page={{ i }}">{{ i+1 }}</a></li>
                        {% endfor %}
                    {% endif %}
                    {# <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li> #}
                
                </ul>
            </nav>

            {% endif %}
</div>

     
{% endblock %}

templates/default/sujet.html.twig
{% extends 'base.html.twig' %}


{% block title %}Gourdy - {{ sujet.titre }}{% endblock %}

{% block body %}
{# <div class="container pt-5">
    <div class="card">
        <div class="card-header bg-gradient bg-info">
            <h1>{{ sujet.titre }}</h1>
            <div class="col d-inline">
                <img class="img rounded-circle width:100%" width="50" height="50" src="../avatars/{{ sujet.user.avatar }}">
            </div>
            <div class="col d-inline">
                par <b>{{ sujet.user.pseudo }}</b> <br>
                <small class="text-muted">le {{ sujet.dateCreation|date("d/m/Y à H:i:s") }}</small>
             
            </div>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <p>{{ sujet.contenu }}</p>
            </blockquote>
        </div>
    </div>
</div> #}

<div class="container py-5">
    <div class="toast-header text-dark mt-2 bg-info bg-gradient">
        <img width="50" height="50" src="../avatars/{{ sujet.user.avatar }}" class="rounded me-2 rounded-circle" alt="...">
        
        <strong class="me-auto">{{ sujet.user.pseudo }} {% if sujet.user.roles[0] == 'ROLE_ADMIN' %}<span class="badge bg-danger">Admin</span>{% endif %}</strong>
        <small class="text-muted">le {{ sujet.dateCreation|date("d/m/Y à H:i:s") }}</small>
    </div>
    <div class="toast-body bg-light">
    <h2>{{ sujet.titre }}</h2>
        {{ sujet.contenu }}
    </div>
</div>
<div class="container mt-3">
    {% set cpt = 0 %}
    {% set page = app.request.get('page') %}
    {% set nbComm = page*8 %}

    {% if sujet.commentaires|slice(nbComm, 8) is empty and page >= 1 %}
    <script>
        location.replace("{{ sujet.id }}");
    </script>
    {% endif %}

    {% for commentaire in sujet.commentaires|slice(nbComm, 8) %}
        {# <div class="card mt-1">
            <div class="container p-3 bg-gradient" {% if commentaire.user.roles[0] == 'ROLE_ADMIN' %} style="background-color:red;" {% elseif cpt is divisible by(2) %} style="background-color:#3cb371" {% else %} style="background-color:#20c997" {% endif %}>
                <div class="col d-inline">
                
                    <img class="img rounded-circle" width="50px" height="50px"  src="../avatars/{{ commentaire.user.avatar }}">
                    <div class="col d-inline">
                        Par <b> {{ commentaire.user.pseudo }} </b>  {% if commentaire.user.roles[0] == 'ROLE_ADMIN' %} - Admin{% endif %} <br>
                        <small class="text-muted d-inline">le {{ commentaire.dateCommentaire|date("d/m/Y à H:i:s") }}</small>
                    </div>
                    {% if is_granted ('ROLE_ADMIN') %}
                    <div class="text-right">
                        <a class="btn btn-primary" href="{{ path('delete_Commentaire', {'id':commentaire.id }) }}">Supprimer</a>
                    </div>
                    {% endif %}
                </div>
            </div> #}
        {% if commentaire.isDelete %}
            <div class="toast-header text-dark mt-3 bg-gradient" {% if cpt is divisible by(2) %} style="background-color:#3cb371" {% else %} style="background-color:#20c997" {% endif %}>
                <img width="50" height="50" src="../avatars/{{ commentaire.user.avatar }}" class="rounded me-2 rounded-circle" alt="...">
                <strong class="me-auto">{{ commentaire.user.pseudo }} {% if commentaire.user.roles[0] == 'ROLE_ADMIN' %}<span class="badge bg-danger">Admin</span>{% endif %}</strong>
                <small class="text-muted">le {{ commentaire.dateCommentaire|date("d/m/Y à H:i:s") }}</small>
            </div>
            <div class="toast-body bg-light">
                <small class="text-muted">Ce message a été supprimé par un admin.</small>
            </div>
        {% else %}
            <div class="toast-header text-dark mt-3 bg-gradient" {% if cpt is divisible by(2) %} style="background-color:#3cb371" {% else %} style="background-color:#20c997" {% endif %}>
                <img width="50" height="50" src="../avatars/{{ commentaire.user.avatar }}" class="rounded me-2 rounded-circle" alt="...">
                <strong class="me-auto">{{ commentaire.user.pseudo }} {% if commentaire.user.roles[0] == 'ROLE_ADMIN' %}<span class="badge bg-danger">Admin</span>{% endif %}
                    {% if app.user and app.user.email == commentaire.user.email or is_granted ('ROLE_ADMIN') %}
                    <a class="btn btn-primary" href="{{ path('edit_Commentaire', {'id':commentaire.id}) }}">Modifier</a>
                    {% endif %}</strong>
                <small class="text-muted">le {{ commentaire.dateCommentaire|date("d/m/Y à H:i:s") }}</small>
            </div>
            <div class="toast-body bg-light">
                {{ commentaire.contenu }}
                {% if commentaire.isEdited == true %}<br><br>
                    <small class="text-muted">Ce message a été modifié le {{ commentaire.dateModification|date("d/m/Y à H:i:s") }}</small>
                {% endif %}
                {% if commentaire.user.signature is not null %}
                    <hr>
                    <small class="text-muted"><b>{{ commentaire.user.signature }}</b></small>
                {% endif %}
            </div>
        {% endif %}
        {% set cpt = (cpt)+1 %}   
    {% endfor %}
            {# <div class="container p-1 bg-gradient" {% if cpt is divisible by(2) %} style="background-color:#3cb371" {% else %} style="background-color:#20c997" {% endif %}>
                <div class="row">
                    <div class="col col-sm-1 align-self-center text-center">
                        <img class="img rounded-circle width:100%" width="50" height="50" src="../avatars/{{ commentaire.user.avatar }}">
                    </div>
                    <div class="col col-sm-2">Par <b> {{ commentaire.auteur }} </b><br>
                        <small class="text-muted">le {{ commentaire.dateCommentaire|date("d/m/Y à H:i:s") }}</small>
                    </div>
                </div>
            </div> #}



            {# <div class="card-header bg-gradient" {% if cpt is divisible by(2) %} style="background-color:#3cb371" {% else %} style="background-color:#20c997" {% endif %}>
                <div>
                    Par <b>{{ commentaire.auteur }}</b><img class="img rounded-circle width:100%" width="50" height="50" src="../avatars/{{ commentaire.user.avatar }}">
                </div>
                <small class="text-muted">envoyé le {{ commentaire.dateCommentaire|date("d/m/Y à H:i:s") }}</small>
            </div> #}

{# 
            <div class="card-body">
                <blockquote class="blockquote mb-0">
                    <p>{{ commentaire.contenu }}</p>
                </blockquote>
            </div> #}

        



    {# <div class="text-center">
        {% if sujet.commentaires|length > 8 %}
            {% set test = sujet.commentaires|length/8%8 %}
            {% if sujet.commentaires|length is divisible by(8) %}
                {% for i in 0..test-1 %}
                    <a class="btn btn-primary {% if page == i %}active{% endif %}" href="?page={{ i }}">{{ i+1 }}</a>
                {% endfor %}
            {% else %}
                {% for i in 0..test %}
                    <a class="btn btn-primary {% if page == i %}active{% endif %}" href="?page={{ i }}">{{ i+1 }}</a> 
                {% endfor %}
            {% endif %}
        {% endif %}
    </div> #}
    {% if sujet.commentaires|length > 8 %}
    <nav>
        <ul class="pagination justify-content-center mt-5">
        
            {% set test = sujet.commentaires|length/8%8 %}
            {% if sujet.commentaires|length is divisible by(8) %}
                {% for i in 0..test-1 %}
            <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="?page={{ i }}">{{ i+1 }}</a></li>
            {% endfor %}
            {% else %}
                {% for i in 0..test %}
                    <li class="page-item {% if page == i %}active{% endif %}"><a class="page-link" href="?page={{ i }}">{{ i+1 }}</a></li>
                {% endfor %}
            {% endif %}
            {# <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li> #}
        
        </ul>
    </nav>
    {% endif %}
</div>
<br><br>

{% if is_granted ('ROLE_USER') and app.user.isVerified == true %}

    <div class="py-1 bg-danger rounded"></div><br><br>
        {{ form_start(form) }}  
        
        
        {{ form_widget(form.contenu, {'attr':{'class':'form-control'}}) }}
        {{ form_rest(form) }}
        <div class="text-center">
            <button type="submit" class="btn btn-primary mt-2 mb-5">Envoyer</button>
        </div>
        {{ form_end(form) }}
{% elseif app.user == false %}
    <div class="text-center">
        <a class="btn btn-primary" href="{{ path('app_login') }}">Vous devez être connecté pour envoyer des messages.</a>
    </div><br>
{% elseif app.user.isVerified == false %}
    <div class="text-center">
        <a class="btn btn-primary" href="{{ path('app_login') }}">Vous devez valider votre adresse mail pour envoyer des messages.</a>
    </div><br>
{% endif %}

{# <script>
      let modalBtns = [...document.querySelectorAll(".button")];
      modalBtns.forEach(function (btn) {
        btn.onclick = function () {
          let modal = btn.getAttribute("data-modal");
          document.getElementById(modal).style.display = "block";
        };
      });
      let closeBtns = [...document.querySelectorAll(".close")];
      closeBtns.forEach(function (btn) {
        btn.onclick = function () {
          let modal = btn.closest(".modal");
          modal.style.display = "none";
        };
      });
      window.onclick = function (event) {
        if (event.target.className === "modal") {
          event.target.style.display = "none";
        }
      };
    </script> #}


{% endblock %}